version: '3.4'

services:

  identity-api:
    image: ${REGISTRY:-lsac}/identityapi:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Identity.API/Dockerfile

  identity.blazorclient:
    image: ${REGISTRY:-lsac}/ssodemo:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Identity.BlazorClient/Dockerfile
    depends_on:
      - identity-api
