version: '3.4'

# The default docker-compose.override file can use the "localhost" as the external name for testing web apps within the same dev machine.
# The ESHOP_EXTERNAL_DNS_NAME_OR_IP environment variable is taken, by default, from the ".env" file defined like:
#     ESHOP_EXTERNAL_DNS_NAME_OR_IP=localhost
# but values present in the environment vars at runtime will always override those defined inside the .env file
# An external IP or DNS name has to be used (instead localhost and the 10.0.75.1 IP) when testing the Web apps and the Xamarin apps from remote machines/devices using the same WiFi, for instance.

services:

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Development=true 
      - ASPNETCORE_URLS=http://+;https://+
      - ConnectionStrings__IdentityDb=Host=localhost;Database=ssodemo;Username=postgres;Password=yugabyte;Port=5432
      - UseCustomizationData=True
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - Kestrel__Certificates__Default__Password=password
    ports:
      - "6051:443"
      - "6050:80"
    volumes:
      - ~/.aspnet/https:/https:ro
    networks:
      - devnet

  identity.blazorclient:
    ports:
      - 5000:80
    networks:
      - devnet

networks:
    devnet:
        external: true


