version: '3.4'

# The default docker-compose.override file can use the "localhost" as the external name for testing web apps within the same dev machine.
# The ESHOP_EXTERNAL_DNS_NAME_OR_IP environment variable is taken, by default, from the ".env" file defined like:
#     ESHOP_EXTERNAL_DNS_NAME_OR_IP=localhost
# but values present in the environment vars at runtime will always override those defined inside the .env file
# An external IP or DNS name has to be used (instead localhost and the 10.0.75.1 IP) when testing the Web apps and the Xamarin apps from remote machines/devices using the same WiFi, for instance.

services:
  sqldata:
    command: bin/yugabyted start --base_dir=/home/yugabyte/yb_data --daemon=false
    ports:
      - 7000:7000
      - 9000:9000
      - 5433:5433
      - 9042:9042
    networks:
      - devnet
    volumes:
     - yb-data:/home/yugabyte/yb_data

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Development=true 
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionStrings__IdentityDb=Host=${EXTERNAL_DNS_NAME_OR_IP};Database=identity;Username=yugabyte;Password=yugabyte;Port=5433
      - UseCustomizationData=True
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - Identity__Host=http://127.0.0.1:5105
    ports:
      - "5105:80"
    networks:
      - devnet

  identity.blazorclient:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Identity__Host=http://127.0.0.1:5105
    ports:
      - "80:80"
    networks:
      - devnet

volumes:
  yb-data:

networks:
  devnet:
    external: true      


